# Generated by Django 5.0.6 on 2024-06-08 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 22, 30, 27, 420895)),
        ),
    ]
