# Generated by Django 5.0.6 on 2024-06-08 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 8, 22, 34, 9, 530229), null=True),
        ),
    ]
